[core]
  engine = pg
  top_dir = .
  plan_file = sqitch.plan

[engine "pg"]
  target = db:pg://postgres:postgres@localhost:5432/sqitch_demo_db

[target "dev"]
  uri = db:pg://postgres:postgres@localhost:5432/sqitch_demo_db
